language: go

sudo: required
dist: xenial
go:
  - 1.12.9

env:
  global:
    - GO111MODULE=on

jobs:
  include:
    - stage: "Unit tests"
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)